a=int(input("enter the number:"))
b=int(input("enter the number:"))
print("addition:",a+b)
print("substraction:",a-b)
print("multiplication:",a*b)
print("division:",a/b)
print("modulus:",a%b)
print("expoentional:",a**b)
print("floor division:",a//b)
